name: Autp Close Pull Request
on:
  pull_request_target:
    types: [ opened, reopened ]
    paths:
      - 'keys.json'
      - 'macros.dtsi'
      - '.Adv360/**'
      - 'firmware/2*.uf2'
      - 'template.keymap'

jobs:
  auto-close:
    runs-on: ubuntu-latest
    steps:
      - uses: superbrothers/close-pull-request@v3
        with:
          # Optional. Post a issue comment just before closing a pull request.
          comment: "We do not accept PRs that change keymap, macros, .Adv360, or firmware files."
